---
title: "Functions Workshop"
output: html_document
---

## Overview
- What we're going to discuss today

## Why Functions?
- What purpose do they serve?
- When do you need to use one?

## Basic Structure
- Share an example and talk through the pieces

> * hands-on, beginner: take the example and run it, see what it does, and make sure you know why it does that
* hands-on, advanced: take a snippet of code you have used in the past that produces a result, and wrap it up to be a function without any input or return just yet.

## What Goes In
- How you shape inputs to functions, knowing what objects and types you want to accept
- Accepting lists of objects

> * hands-on, beginner: take new example, try passing in a single obj versus a list 
* hands-on, advanced: add an input argument to your new function, decide what it should be, and see how it works.

## What Comes Out
- What to return, what types and objects you can give back
- Giving back lists of objects

> * hands-on, beginner: change the example so it returns a list
* hands-on, advanced: decide what kind of result your function should return, and add this element

## Setting Guardrails
- Documentation
- Typing
- Testing inputs and returning errors
- Writing tests for your functions

> * hands-on, beginner: given an example function, write your own docstring
* hands-on, beginner: given an example function, write your own test
* hands-on, advanced: add a docstring to your function
* hands-on, advanced: add a chunk of code to your function to test an attribute of the input

## Combining Functions
- Multiple functions to get to the end result

## Conclusions

## Links
* https://nicercode.github.io/guides/functions/
